// 아이콘 갤러리 데이터 — lucide 아이콘을 카테고리별로 정리한 카탈로그.
// 각 아이콘은 lucide 공식 사이트(https://lucide.dev/icons/{name})로 연결된다.
// 이름(name)은 lucide-react가 제공하는 IconName 유니온 타입이라, 존재하지 않는
// 아이콘 이름을 쓰면 컴파일 단계에서 걸러진다. 실제 렌더링은
// lucide-react/dynamic 의 DynamicIcon(지연 로딩)이 담당한다.

import type { IconName } from "lucide-react/dynamic";

export const LUCIDE_ICONS_BASE_URL = "https://lucide.dev/icons";

export function iconDocsUrl(name: IconName): string {
  return `${LUCIDE_ICONS_BASE_URL}/${name}`;
}

export type IconCategory = {
  id: string;
  title: string;
  description: string;
  icons: IconName[];
};

export const ICON_GALLERY: IconCategory[] = [
  {
    id: "arrows",
    title: "화살표 & 이동",
    description: "방향·이동·회전을 나타내는 아이콘",
    icons: [
      "arrow-up",
      "arrow-down",
      "arrow-left",
      "arrow-right",
      "arrow-up-right",
      "chevron-down",
      "chevron-right",
      "chevrons-up-down",
      "move",
      "refresh-cw",
      "rotate-cw",
      "corner-down-right",
    ],
  },
  {
    id: "files",
    title: "파일 & 문서",
    description: "파일·폴더·문서 작업 아이콘",
    icons: [
      "file",
      "file-text",
      "files",
      "folder",
      "folder-open",
      "file-plus",
      "file-down",
      "save",
      "copy",
      "clipboard",
      "paperclip",
      "archive",
    ],
  },
  {
    id: "communication",
    title: "커뮤니케이션",
    description: "메일·메시지·알림 등 소통 아이콘",
    icons: [
      "mail",
      "message-square",
      "message-circle",
      "send",
      "bell",
      "phone",
      "at-sign",
      "inbox",
      "reply",
      "share-2",
      "megaphone",
      "mic",
    ],
  },
  {
    id: "multimedia",
    title: "미디어 & 재생",
    description: "재생·음량·사진·영상 아이콘",
    icons: [
      "play",
      "pause",
      "skip-forward",
      "skip-back",
      "volume-2",
      "volume-x",
      "image",
      "video",
      "music",
      "camera",
      "film",
      "mic",
    ],
  },
  {
    id: "text",
    title: "텍스트 & 편집",
    description: "서식·정렬 등 텍스트 편집 아이콘",
    icons: [
      "pencil",
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "list",
      "list-ordered",
      "align-left",
      "align-center",
      "type",
      "quote",
      "copy",
    ],
  },
  {
    id: "layout",
    title: "레이아웃 & UI",
    description: "화면 배치·메뉴·컨트롤 아이콘",
    icons: [
      "layout-dashboard",
      "layout-grid",
      "columns-3",
      "rows-3",
      "panel-left",
      "maximize",
      "minimize",
      "menu",
      "more-horizontal",
      "more-vertical",
      "grip",
      "settings",
    ],
  },
  {
    id: "account",
    title: "사용자 & 계정",
    description: "사용자·인증·보안 아이콘",
    icons: [
      "user",
      "users",
      "user-plus",
      "user-check",
      "user-x",
      "contact",
      "log-in",
      "log-out",
      "settings",
      "shield",
      "key",
      "badge-check",
    ],
  },
  {
    id: "finance",
    title: "커머스 & 금융",
    description: "쇼핑·결제·통계 아이콘",
    icons: [
      "shopping-cart",
      "shopping-bag",
      "credit-card",
      "wallet",
      "dollar-sign",
      "tag",
      "gift",
      "package",
      "receipt",
      "banknote",
      "percent",
      "trending-up",
    ],
  },
  {
    id: "weather",
    title: "날씨 & 자연",
    description: "날씨·자연·계절 아이콘",
    icons: [
      "sun",
      "moon",
      "cloud",
      "cloud-rain",
      "snowflake",
      "wind",
      "droplet",
      "leaf",
      "flame",
      "star",
      "zap",
      "globe",
    ],
  },
  {
    id: "devices",
    title: "기기 & 하드웨어",
    description: "단말·주변기기·연결 아이콘",
    icons: [
      "smartphone",
      "tablet",
      "laptop",
      "monitor",
      "keyboard",
      "mouse",
      "printer",
      "server",
      "hard-drive",
      "wifi",
      "bluetooth",
      "battery",
    ],
  },
  {
    id: "status",
    title: "상태 & 알림",
    description: "성공·경고·정보 등 상태 아이콘",
    icons: [
      "check",
      "x",
      "info",
      "triangle-alert",
      "circle-alert",
      "circle-check",
      "circle-x",
      "circle-help",
      "ban",
      "loader",
      "bell-ring",
      "badge-check",
    ],
  },
  {
    id: "maps",
    title: "지도 & 이동수단",
    description: "위치·지도·교통수단 아이콘",
    icons: [
      "map",
      "map-pin",
      "navigation",
      "compass",
      "globe",
      "car",
      "plane",
      "bike",
      "flag",
      "route",
      "locate",
      "arrow-up-right",
    ],
  },
];
